# Generated by Django 4.0.4 on 2022-07-26 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(max_length=500)),
                ('selectedCategory', models.CharField(choices=[('a', 'Academics'), ('s', 'Sports'), ('e', 'Entertainment'), ('w', 'Work'), ('fam', 'Family'), ('sg', 'Self-growth'), ('fri', 'Friend'), ('shop', 'Shopping'), ('h', 'Health'), ('t', 'Travel')], max_length=4)),
                ('assignedDate', models.DateTimeField()),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.calender')),
            ],
            options={
                'ordering': ['-assignedDate'],
            },
        ),
    ]
